name: Main Branch Workflow
on:
  push:
    branches:
      - main
jobs:
  multi-action-job:
    runs-on: ubuntu-latest
    steps:
      - uses: slashben/multiple-actions-example/start@main
        name: Start Script
      - uses: slashben/multiple-actions-example/stop@main
        name: Stop Script
